### ISSUE TITLE
Not enough permissions to access: GET-handleString /clientAwareMemberHandles

### ISSUE THREAD

**Issue by mingxin-yang** [linkedin-developers/linkedin-api-js-client#18]
Hello developers, I want to use the api `GET https://api.linkedin.com/v2/clientAwareMemberHandles?q=handleString&handleString={someone@email.com}
` in this `https://learn.microsoft.com/en-us/linkedin/shared/integrations/people/handle-lookup`, but the prompt does not have permission, how should I get it, I do not have it Found in the docs, you guys can help us, thanks everyone

**Comment by shimizust** [comment]
Hi @mingxin-yang, this isn't an issue related to the api client itself, so closing it. But generally these restricted APIs are meant for select, strategic partners. For questions related to API access, you can create a ticket at linkedin.zendesk.com. Hope that helps.
