### ISSUE TITLE
LinkedIn OpenAPI/Swagger specification?

### ISSUE THREAD

**Issue by fab-mindflow** [linkedin-developers/linkedin-api-js-client#24]
Hey there,
Any OpenAPI/swagger specification of all LinkedIn APIs available?
Or a rest.li converter?

**Comment by shimizust** [comment]
@fab-mindflow Unfortunately, LinkedIn APIs cannot actually be fully represented using the OpenAPI spec due to the specifics of the Rest.li protocol. Very simple APIs can be represented by OpenAPI spec, but not any of medium complexity.

**Comment by fab-mindflow** [comment]
OK, noted. Yes, OpenAPI has limitations and for LinkedIn scale, I understand it's quite a challenge. However, OpenAPI is also the most popular API standard (being extended along the way) and successfully used by a lot of small and large vendors and clients. Covering most important endpoints would be quite handy to ease integrations.
